root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "web", "bin", ".vite"]
exclude_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
rerun = false
rerun_delay = 500

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
