root = "."
tmp_dir = "tmp"

[build]
args_bin = []
# seed 108154 2132143 87461333
bin = "./tmp/main -noaudio"
cmd = "go build -o ./tmp/main ./game"
delay = 1000
exclude_dir = ["web", "bin", ".vite", "sprite-editor", "site", "etc"]
include_ext = ["go", "yaml"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
rerun = false
rerun_delay = 500

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
