name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.0'

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        run: make lint

      - name: Check build works
        run: make build-bin
